ZerBea/hcxdumptool

Makefile
=> Makefile: fix typo

AndroidManifest.xml, README.md
I fixed AndroidMainfest.xml so build will not spam whole terminal.
=> Android NDK fixes

usefulscripts/bash_profile
Remove deprecated parameters from bash_profile
=> Remove non-existing args from the sample

hcxdumptool.c
Unless you have a special reason for using "incomming" instead of "incoming" I think it's a typo. At least it annoys me after a while seeing it.
=> Fix typo(?)

README.md
I needed to add these commands and additions to make `make` work.
=> Add information how to install on ubuntu 18.04

README.md
Although trivial, having complete instructions may help.
=> Elaborate Compile instructions

hcxdumptool.c
- some functions had to be moved around 
- the filename variables had to be made global as they need to be accessed outside main()
- loading and reloading is handled by new loadfiles()
- readextbeaconlist() had to be modified to handle lists depending on --active_beacon flag: 
- rglist is extended by new essids only to not lose collected ones
- rgbeaconlist is reread completely
resolves #122
=> Add reloading of BPF, mac filter and ESSID lists on SIGHUP

hcxdumptool.c, include/hcxdumptool.h
This function establishes a TLS tunnel over EAP, when there is a PEAP request send out with an --eapreq sequence to connecting clients using WPA Enterprise and the client accepts this request. Further EAP requests will be send through this tunnel as EAP Phase 2 authentication packets.
It is mandatory to pass a TLS server certificate in PEM format and the server key to the respective options --eap_server_cert and --eap_server_key.
New option --eapoleaptimeout sets the overall timeout for an entire EAP connection sequence.
- a request to return a possibly available client certificate is send during handshake
- maximum negotiated TLS version is intentionally limited to TLSv1.2 to receive an unencrypted client certificate to store to the pcapng file
- new function in process_fd() that resends …
=> Add new option --eaptlstun to establish TLS tunnel over EAP

hcxdumptool.c
- set EAP type in first request
- fixed eapreq example MSCHAPV2 request
=> Fix --eapreq sending null type in first request

README.md
Fixed some minor spelling issues in the readme.
=> fix spelling in readme

README.md
`hcxdumptool` is not part of the `hcxtools` package so I fixed it in the readme.
```
[ blackarch ~ ]# pacman -Sy
:: Synchronizing package databases...
core                                                 154.0 KiB  24.9 KiB/s 00:06 [##############################################] 100%
extra                                               1746.0 KiB   310 KiB/s 00:06 [##############################################] 100%
community                                              7.2 MiB  1452 KiB/s 00:05 [##############################################] 100%
multilib                                             161.2 KiB   130 KiB/s 00:01 [##############################################] 100%
blackarch                                              3.8 MiB  5.73 MiB/s 00:01 …
```
=> fix package name in readme

README.md
Funny typo, working too much with packets I guess :)
=> fix typo in readme (packet manager)

hcxdumptool.c
=> Code optimization

hcxdumptool.c, usefulscripts/startnm, usefulscripts/stopnm
* Fix shadowed symbols (NEEDs to be reviewed!)
* Translate startnm and stopnm from german to english
=> Minor fixes

hcxdumptool.c
Replaced some magic numbers in `writegpwpl()`.
=> replace some magic numbers in writegpwpl()

hcxdumptool.c
My IDE keeps complaining about these unsorted includes so I sorted them in alphabetic order.
=> sort includes

hcxdumptool.c
Handle smaller screen in a better way :+1:
=> Merge changes

hcxdumptool.c
=> fix musl compilation

README.md
I rewrote the README.md for clarity when reading. Some information was changed/added, but most remains the same when compared to the original.
=> Rewriten version of README.md

README.md
It seems that stopnm and startnm script descriptions were switched.
=> Small correction of "Useful Scripts" section on README.md
