- hcxdumptool.c
Change the default extension of the rotate files to cap instead of pcap in order to be compatible with the file extension restrictions of DWPA.
> Change the default extension to cap instead of pcap

- Makefile
Make by default supports CPPFLAGS as well, adding them to the custom
targets aids distro packaging as they define certain things in CPPFLAGS.
> make: support standard CPPFLAGS to aid distro packaging

- hcxdumptool.c
The first octet LSB bit determines if the mac is a unicast (0) or multicast (1)
The first octet Second LSB bit determines if the mac is global unique (0) or locally administered (1)
https://en.wikipedia.org/wiki/MAC_address#/media/File:MAC-48_Address.svg
Having those bits set can raise suspicion, the locally administered sometimes are used by enterprise access points though.
> Generate a random bssid/mac with unicast bit 0 and global unique

- hcxdumptool.c
- include/hcxdumptool.h
- include/strings.c
- pulled the default beacon content into `make_beacon_tagparams()` to prepare beacon IEs at startup
- testing and reading --beaconparams argument hex string in `ietag_t` data structure using `bin2ieset()`
- merge new IEs into default beacon data with `merge_ieset2bin()`
`--beaconparams=<TLVs>              : update or add Information Elements in all transmitted beacons`
`                                                        maximum 50 IEs as TLV hex string, tag id 0 (ESSID) will be ignored, tag id 3 (channel) overwritten`
`                                                        multiple IEs with same tag id are added, default IE is overwritten by the first`
resolves #126
> Add new option --beaconparams to add or change IEs in transmitted beacons

- hcxdumptool.c
- include/hcxdumptool.h
This function sends out arbitrary EAP Requests that are given as comma separated hex strings with an optional termination flag.
- the EAP Request sequence is send out for every network that is associated as a WPA-Enterprise network by the client
- every response by the client to a request is responded to by a default or choosen terminating EAP status, client deauthentication or no packet
- if the sequence is interrupted and the client reconnects using the same ESSID, the sequence will be resumed
- the EAP Request sequence is reset every time the client associates with a different ESSID
- WPA-PSK associations are handled as usual
Caveats when using this function:
- clients will be authenticated every time they request, even if their status suggests they would be ignored otherwise
- clients …
> Add new option --eapreq to send EAP Requests to WPA-Enterprise clients

- hcxdumptool.c
- include/hcxdumptool.h
- added mode prefix to bind requests to established TLS tunnel
restarted EAP connection (renewed ASSOC) at request state with T mode prefix will try to go back to last non-prefix (usually TLS starting) request
- fixed EAP request state handling
- fixed packet writing of sent packets over TLS
- updated examples
> Added mode prefix to --eapreq definition to send EAP requests only over established TLS tunnel

- hcxdumptool.c
In send_association_req_wpa2() and send_reassociation_req_wpa2() AKM suite is set to PSK-SHA256 using bitfield addressing TAK_PSKSHA256 (32) instead of AK_PSKSHA256 (6).
> Fix setting AKM suite to PSK-SHA256

- hcxdumptool.c
- compiles with older OpenSSL versions like 1.0.2, as still used e.g. in OpenWRT
> Fix for compatibility issue with OpenSSL < 1.1.0

- hcxdumptool.c
- include/pcap.c
- if pcapng output file option is given as '-o -', all pcapng data will be send to stdout
- all usual output to stdout (e.g. printf) will be muted, stderr is not affected
- stdout will be checked for being a terminal and if so, an exiting error will be thrown
> Added facility to output pcapng file to stdout

- hcxdumptool.c
- stdout cannot be reassigned on some systems i.e OpenWRT on mipsel
> fix assignment of read-only variable 'stdout'

- hcxdumptool.c
- reassigns file descriptor for pcapng output to stdout fd
- exchanges stdout file descriptor with fd pointing to /dev/null
- doesn't reassign symbol `stdout` directly, which is not guaranteed to work by C standards and breaks on some stdio.h implementations
- fixes ZerBea/hcxdumptool#166
> fixed reassignment of stdout for portability

- hcxdumptool.c
- removed pointlessly doubled stdout reassignment that used non-portable way of assinment as already solved in #168
- fixed writing pcapng to stdout in client mode
fixes #171
> fixed reassignment of stdout in client mode

- README.md
I have been using this interface with hcxdumptool for some time already and never had any issues. It requires you to run "iw dev \<interface\> set type monitor" before starting hcxdumptool or packet injection won't work, but other than that, it works fine. I've only tested it with the [aircrack-ng rtl8812au driver](https://github.com/aircrack-ng/rtl8812au) on 5.10.41-1-MANJARO but I don't think there will be issues on other distros. If this gets merged, I will also add it in the [Wiki section](https://github.com/ZerBea/hcxdumptool/wiki/WiFi-Adapters).
> Add ALFA AWUS036ACH to list of supported wifi adapters

- hcxdumptool.c
- include/hcxdumptool.h
- with `--eapreq_follownak` hcxdumptool will jump to the next EAP request entry contained in the sequence passed to `--eapreq` with a type matching the Desired Auth Type requested in a client's Legacy NAK response
- only remaining entries are considered, already processed ones will be not
- a Desired Auth Type not contained in the remaining sequence will be ignored, the sequence will be continued onward
> Added EAP option to follow Auth Type requested in Legacy NAK response

- hcxdumptool.c
On my rtl8814a adapter, iwr.u.name is "IEEE 802.11AC" (or disabling the 5ghz band will appear as "IEEE 802.11bgn"). Using IF_NAMESIZE, a maximum of 16 chars (null termination) is compared.
> Fix WEXT verification on some devices

- README.md
Same as https://github.com/ZerBea/hcxtools/pull/256 just for this repo.
```
$ sudo make install PREFIX=/usr/local                  
install -D -m 0755 hcxdumptool /usr/local/bin/hcxdumptool
install -D -m 0755 hcxpioff /usr/local/bin/hcxpioff
```
> extend 'make install' instructions

- hcxdumptool.c
```
$ sudo ./hcxdumptool -i wlp0s20f0u1 -t 1                
hold time must be > 2 secondsn
```
'secondsn' --> 'seconds'
> fix typo in holdtime error message

- hcxdumptool.c
`errorcountmax` is unsued currently meaning the value set with `--errormax=` is ignored and `ERROR_MAX` is hardcoded instead. Now this is fixed. The error message displayed when an incorrect value is set with `--errormax=` is also fixed.
> fix errorcountmax usage and error message

- README.md
`NETLINK` is supported since https://github.com/ZerBea/hcxdumptool/commit/311e09325d70a0774d25f687b285c3af26ca7519, lets update the readme
> remove NETLINK from unsupported list

- README.md
`pkg-config` `libcurl4-openssl-dev` `libssl-dev` are not necessary anymore (since https://github.com/ZerBea/hcxdumptool/commit/d1f23265349bae552659e964cfb7f2953548d93a and https://github.com/ZerBea/hcxdumptool/commit/311e09325d70a0774d25f687b285c3af26ca7519), `zlib1g-dev` has never been required, I think it was just copied from `hcxtools`, so lets remove them.
> update Debian package requirements

- .gitignore
- README.md
- man/hcxdumptool.1
`hcxpioff.c` has been removed in https://github.com/ZerBea/hcxdumptool/commit/311e09325d70a0774d25f687b285c3af26ca7519, lets update `.gitignore`, `manpage` and `README.md` also
> remove deprecated hcxpioff from .gitignore, manpage and readme

- hcxdumptool.c
Removed a check which is never hit.
```
$ sudo ./hcxdumptool --gpio_button=2 --gpio_statusled=2
invalid GPIO option
```
--> The program fails during the option parsing already so the removed code is never executed.
> simplify GPIO pin validation

- hcxdumptool.c
For new users it might not be obvious which option is not compatible with `--nmea_dev=`/`--gpsd` if there is a lot of command line options specified at the same time:
```
$ sudo ./hcxdumptool -i wlp0s20f0u1 --gpsd --nmea_dev=/dev/ttyACM0 --gpio_button=4 --gpio_statusled=17 --onsigterm=exit --ongpiobutton=poweroff --ontot=reboot --onerror=reboot --onwatchdog=reboot --bpf=protect.bpfc --essidlist=standard.essidliste --attemptapmax=1000
not allowed in combination with gpsd
```
so I made it more clear:
```
$ sudo ./hcxdumptool -i wlp0s20f0u1 --nmea_dev=/dev/ttyACM0 --gpsd
gpsd not allowed in combination with nmea_dev
$ sudo ./hcxdumptool -i wlp0s20f0u1 --gpsd --nmea_dev=/dev/ttyACM0
nmea_dev not allowed in combination with gpsd
```
> make error message more obvious when --nmea_dev= + --gpsd are specified

- hcxdumptool.c
Both my IDE and `clang` keep complaining about this `pa` unused variable so I removed it.
> remove unused variable in show_realtime_rca()

- hcxdumptool.c
I think in `read_bpf()` we should return `false` on all errors and let `open_socket_rx()` handle the return value:
```
static bool read_bpf(char *bpfname)
{
...
if((fh_filter = fopen(bpfname, "r")) == NULL) return false;
if((len = fgetline(fh_filter, 128, linein)) < 0) return false;
sscanf(linein, "%"SCNu16, &bpf.len);
if(bpf.len == 0) return false;
bpf.filter = (struct sock_filter*)calloc(bpf.len, sizeof(struct sock_filter));
c = 0;
bpfptr = bpf.filter;
while(c < bpf.len)
{
if((len = fgetline(fh_filter, 128, linein)) == -1)
{
bpf.len = 0;
break;
}
sscanf(linein, "%" SCNu16 "%" SCNu8 "%" SCNu8 "%" SCNu32, &bpfptr->code, &bpfptr->jt, &bpfptr->jf, &bpfptr->k);
bpfptr++;
c++;
}
if(bpf.len != c) return false;
fclose(fh_filter);
return true;
}
```
```
static bool open_socket_rx(char *bpfname) …
```
> exit always when read_bpf() fails

- README.md
Updated obsolete chapter 'procedure' in the readme.
```
$ sudo ./hcxdumptool -i wlp0s20f0u1 --rca_scan       
./hcxdumptool: unrecognized option '--rca_scan'
hcxdumptool 6.2.9 (C) 2023 by ZeroBeat
usage: hcxdumptool -h for help
```
> update procedure in readme

- hcxdumptool.c
Removed the definition of `ioctl_set_frequency()` since it has been replaced with `nl_set_frequency()`.
> remove obsolete unused function ioctl_set_frequency()

- hcxdumptool.c
I am playing with the NMEA code currently. This is a follow-up of #272 where `void` has been added to the function definitions but `process_nmea0183()` has been left out.
> add void keyword to process_nmea0183()

- hcxdumptool.c
Is there any specific reason not to exit when NMEA or GPSD open fails?
Currently `hcxdumptool` still starts, prints a warning message though but it happens fast so we (at least me) might not always notice it:
```
$ sudo ./hcxdumptool -i wlp0s20f0u1u2 --nmea_dev=/dev/ttyACM0
Requesting interface capabilities. This may take some time.
Please be patient...
failed to open NMEA0183 device
interface information:
...
This is a highly experimental penetration testing tool!
It is made to detect vulnerabilities in your NETWORK mercilessly!
BPF is unset! Make sure hcxdumptool is running in a 100% controlled environment!
Initialize main scan loop...^C
1 errors during runtime
bye-bye
```
I think exit would be better:
```
$ sudo ./hcxdumptool -i wlp0s20f0u1u2 --nmea_dev=/dev/ttyACM0
Requesting …
```
> exit if NMEA or GPSD open fails

- Android.mk
- README.md
Android build was broken so I fixed it, readme was obsolete so it is also updated:
Submodule `include/android-ifaddrs` has been dropped in https://github.com/ZerBea/hcxdumptool/commit/311e09325d70a0774d25f687b285c3af26ca7519 so an empty `.gitmodules` has been left behind. Now it is also dropped, and readme is updated: no recursive clone is necessary anymore since this was the only submodule. Build instructions has been made more verbose as well. I did not test any of the built executables though because I am not interested in that.
> android cleanup

- README.md
Android build warnings have been fixed in https://github.com/ZerBea/hcxdumptool/commit/3d9fae0cf55f4f1794a990d408c3ef7f57a01d28 and #299, lets remove the noise from the readme.
> remove noise from Android build instructions in readme

- hcxdumptool.c
This is a follow-up of https://github.com/ZerBea/hcxdumptool/commit/2bed3d4f78b117970dfe2d15e52516c69d55589a which is a really good feature I wanted for quite some time. The display header is a bit misleading though in the current implementation and always says `ESSID (last seen on top)`, even if `--rds=1` is specified.
> add sorting info to display header

- hcxdumptool.c
Fixed a copy-paste error in the `init_lists()` related error message. It is very unlikely these `calloc` calls would fail anytime but lets clean up the message anyway.
> fix init_lists() related error message

- hcxdumptool.c
`ioctl()` calls have been removed in https://github.com/ZerBea/hcxdumptool/commit/7c353a7a63d6f95f0e85522a63eb373f282b1da4 so this include is not necessary anymore.
> remove unused ioctl include

- include/hcxdumptool.h
When building with `clang` we get this warning:
```
$ make CC=clang
fatal: No names found, cannot describe anything.
clang -O3 -Wall -Wextra -Wpedantic -std=gnu99   -o hcxdumptool hcxdumptool.c -DVERSION_TAG=\"6.3.2\" -DVERSION_YEAR=\"2023\" -DSTATUSOUT -DNMEAOUT
In file included from hcxdumptool.c:40:
./include/hcxdumptool.h:336:36: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
static inline bool nl_set_frequency();
^
void
1 warning generated.
```
Now it is fixed.
> fix function declaration related warning

- hcxdumptool.c
Previously when compiled with `clang` the version check returned this misleading `gcc` version:
```
$ ./hcxdumptool -v
hcxdumptool 6.3.2 (C) 2023 ZeroBeat
...
compiled by gcc 4.2.1
...
```
I guess it is because `clang` defines the `__GNUC__` macros for some compatibility reasons or something like that.
I think `clang` is becoming more widespread so this case should be handled. Now, after the changes the version check is fixed:
```
$ make CC=clang                                                  
fatal: No names found, cannot describe anything.
clang -O3 -Wall -Wextra -Wpedantic -std=gnu99   -o hcxdumptool hcxdumptool.c -DVERSION_TAG=\"6.3.2\" -DVERSION_YEAR=\"2023\" -DHCXSTATUSOUT -DHCXNMEAOUT
$ ./hcxdumptool -v
...
compiled by clang 17.0.6
...
$ make clean
...
$ make
fatal: No names …
```
> Extend compiler version detection with clang

- README.md
- docs/hardware-mod.md
The style changes were done for easier reading and comprehension. The removal of the **hardware mod** section was to improve reading flow as it felt out of place in the main README. The section was preserved however as it is now located at /docs/hardware-mod.md
> Redone style of README.md

- hcxdumptool.c
Removed unnecessary executable-bit from file permissions while creating files.
Have not seen any purpose or requirement for them to be set. Reading and writing to the file should be enough.
> Do not make pcapng files executable.
